# Generated by Django 3.0.8 on 2020-12-27 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='dateEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='dateStart',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
