# Generated by Django 3.0.8 on 2021-01-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20201227_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='isFeatured',
            field=models.BooleanField(default=False, verbose_name='Is featured'),
        ),
    ]
