# Generated by Django 3.0.8 on 2020-12-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionsAccess', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('products-view', 'Products viewing'), ('orders', 'Orders'), ('customers', 'Customers'), ('cars', 'Cars'), ('staff', 'Staff'), ('stores', 'Stores'), ('coupons', 'Coupons'), ('promotions', 'Promotions')], max_length=67, null=True, verbose_name='Access to')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
