# Generated by Django 3.0.8 on 2020-12-06 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestampCreated', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True, verbose_name='Coupon is active')),
                ('amountLimit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Coupon amount limit')),
                ('amountUsed', models.PositiveIntegerField(default=0, verbose_name='Coupons used')),
                ('limitOnePerCustomer', models.BooleanField(default=True)),
                ('discountType', models.CharField(choices=[('percent', 'percent'), ('amount', 'amount')], default='percent', max_length=20, verbose_name='Discount type')),
                ('discountAmount', models.PositiveIntegerField(verbose_name='Discount amount')),
                ('dateStart', models.DateField(default=datetime.datetime.now)),
                ('dateEnd', models.DateField(blank=True, null=True)),
                ('conditionAmount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum cart size')),
            ],
        ),
    ]
