# Generated by Django 3.0.8 on 2020-11-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20201108_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='conditionType',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='conditionAmount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum cart size'),
        ),
    ]
