# Generated by Django 3.0.8 on 2020-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20201206_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='conditionAmount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum cart spending'),
        ),
    ]
