# Generated by Django 3.0.8 on 2021-01-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20201227_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amountUsed',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of tumes the coupon has been used'),
        ),
    ]
