# Generated by Django 3.0.8 on 2021-01-19 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_auto_20210117_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='dateStart',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='limitOnePerCustomer',
            field=models.BooleanField(default=True, verbose_name='Coupon is limited to 1 time use per customer'),
        ),
    ]
