# Generated by Django 3.0.8 on 2021-01-24 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_merge_20210124_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amountUsed',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of times the coupon has been used'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discountAmount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Discount amount'),
        ),
    ]
