# Generated by Django 3.0.8 on 2020-12-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='ProductBrand',
        ),
    ]
