# Generated by Django 3.0.8 on 2020-12-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201213_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Brand logo'),
        ),
    ]
