# Generated by Django 3.0.8 on 2021-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('Order', 'Order'), ('Signed up', 'Signed up')], max_length=20, unique=True, verbose_name='Page name')),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='page_name',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('About', 'About'), ('T&C', 'T&C')], default=1, max_length=20, verbose_name='Page name'),
            preserve_default=False,
        ),
    ]
