# Generated by Django 3.0.8 on 2021-01-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210104_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
