# Generated by Django 3.0.8 on 2021-01-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_productbrand_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
