# Generated by Django 3.0.8 on 2021-01-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_productbrand_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecontent',
            old_name='page',
            new_name='name',
        ),
    ]
