# Generated by Django 3.0.8 on 2021-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210117_1441'),
        ('pages', '0009_auto_20210113_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True, verbose_name='Is active')),
                ('categories', models.ManyToManyField(blank=True, to='products.Category')),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
