# Generated by Django 3.0.8 on 2021-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_productsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsection',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
