# Generated by Django 3.0.8 on 2021-01-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_productsection_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='subject',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='content',
            field=models.TextField(default='213', verbose_name='Text Block Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='name',
            field=models.CharField(choices=[('Awaiting Bank Transfer', 'Order Confirmed - Awaiting Bank Transfer'), ('Awaiting payment in store', 'Order Confirmed - Awaiting payment in store'), ('Awaiting payment on delivery', 'Order Confirmed - Awaiting payment on delivery'), ('Shipped', 'Order Shipped'), ('Cancelled', 'Order Cancelled'), ('Refunded', 'Order Refunded')], max_length=30, unique=True, verbose_name='Page name'),
        ),
    ]
