# Generated by Django 3.0.8 on 2020-12-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateEdited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Service display name')),
                ('slug', models.SlugField(unique=True, verbose_name='Service slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('price', models.PositiveIntegerField(default=0)),
                ('seoMetaTags', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Tags (separate by comma "," )')),
                ('isVisible', models.BooleanField(default=True, verbose_name='Visible to public')),
                ('relatedCategories', models.ManyToManyField(blank=True, to='products.Category')),
                ('relatedProducts', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
