"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '##6=8ji_(6jt322-15kp+c_j48=e!2k6mtfbyn-c)x@bxdym8e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '165.22.58.179',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'django.contrib.humanize',

    #Created Apps
    'customers.apps.CustomersConfig',
    'products.apps.ProductsConfig',
    'backoffice.apps.BackofficeConfig',
    'pages.apps.PagesConfig',
    'staff.apps.StaffConfig',
    'cars.apps.CarsConfig',
    'stores.apps.StoresConfig',
    'orders.apps.OrdersConfig',
    'coupons.apps.CouponsConfig',
    'promotions.apps.PromotionsConfig',
    'services.apps.ServicesConfig',
    'indodana.apps.IndodanaConfig',

    # 3rd party apps
    'multiselectfield',
    'rest_framework',

    # All Auth apps
    'django.contrib.sites',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'media')
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static', 'static_root')   # todo will need to be chaged in production to S3
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


### ALLAUTH SETTINGS ###
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

SITE_ID = 1

ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True                                      # automatically logs in the user upon signup (it should be within the same session)
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/orders/checkout/'     # redirect after user has confirmed the email
ACCOUNT_SESSION_REMEMBER = True                                                 # sets to always remember the session of the user unless they logout
ACCOUNT_ADAPTER = 'customers.adapter.MyAccountAdapter'                          # provides ability to modify login redirects under customers/adapter.py
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''

LOGIN_REDIRECT_URL = 'customer-profile'
# LOGIN_URL = 'staff-login'

AUTH_USER_MODEL = 'customers.User'   # defining which is the custom user model that shall be followed for auth
ACCOUNT_FORMS = {'signup': 'customers.forms.CustomerSignUpForm'}    # redefining in allauth what is the signup form for customers


### EMAILS CONFIGURATION ###
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  #* email displayed via console only 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'     #! place back to EmailBackend upon deployement

DEFAULT_FROM_EMAIL = 'no-reply@kiosban.com'
EMAIL_HOST = 'mail.indowebdeveloper.com' 
EMAIL_HOST_USER = 'no-reply@kiosban.com'
EMAIL_HOST_PASSWORD = '3bDoI4awr76^53rB'
EMAIL_USE_SSL = True
EMAIL_PORT = 465

# EMAIL_USE_TLS = True  #* alternative to SSL connection
# EMAIL_PORT = 587

## Emails to:
ADMINS = [('Stan', 'stan.kosyakov@gmail.com'),]
MANAGERS = [
    # ('Stan', 'stan.kosyakov@gmail.com'),
    'stan.kosyakov@gmail.com',
]
