# Generated by Django 3.0.8 on 2020-12-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201206_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercar',
            name='carModel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Car model'),
        ),
    ]
