# Generated by Django 3.0.8 on 2020-12-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='houseNumber',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, choices=[('Jakarta', 'Jakarta'), ('Special Region of Yogyakarta', 'Special Region of Yogyakarta'), ('East Kalimantan', 'East Kalimantan'), ('Riau Islands', 'Riau Islands'), ('Bali', 'Bali'), ('Riau', 'Riau'), ('North Sulawesi', 'North Sulawesi'), ('Banten', 'Banten'), ('West Sumatra', 'West Sumatra'), ('West Java', 'West Java'), ('Aceh', 'Aceh'), ('Central Java', 'Central Java'), ('North Sumatra', 'North Sumatra'), ('South Sulawesi', 'South Sulawesi'), ('East Java', 'East Java'), ('Bangka Belitung Islands', 'Bangka Belitung Islands'), ('Bengkulu', 'Bengkulu'), ('Jambi', 'Jambi'), ('Southeast Sulawesi', 'Southeast Sulawesi'), ('North Kalimantan', 'North Kalimantan'), ('Central Kalimantan', 'Central Kalimantan'), ('South Kalimantan', 'South Kalimantan'), ('South Sumatra', 'South Sumatra'), ('Lampung', 'Lampung'), ('Central Sulawesi', 'Central Sulawesi'), ('Maluku', 'Maluku'), ('Gorontalo', 'Gorontalo'), ('North Maluku', 'North Maluku'), ('West Nusa Tenggara', 'West Nusa Tenggara'), ('West Kalimantan', 'West Kalimantan'), ('West Sulawesi', 'West Sulawesi'), ('East Nusa Tenggara', 'East Nusa Tenggara'), ('West Papua', 'West Papua'), ('Papua', 'Papua')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[('home', 'home'), ('work', 'work')], default='home', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
