# Generated by Django 3.0.8 on 2021-01-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201227_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.PositiveIntegerField(blank=True, max_length=5, null=True),
        ),
    ]
