# Generated by Django 3.0.8 on 2021-01-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210119_2131'),
        ('customers', '0003_auto_20210117_1700'),
    ]

    operations = [
    ]
