# Generated by Django 3.0.8 on 2021-01-27 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_merge_20210124_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipCode',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
