# Generated by Django 3.0.8 on 2020-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentOption',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Payment in the store', 'Payment in the store'), ('Indodana', 'Indodana')], max_length=30, null=True, verbose_name='Payment option'),
        ),
    ]
