# Generated by Django 3.0.8 on 2020-11-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='createdBy',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='purchasePrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
