# Generated by Django 3.0.8 on 2020-11-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201108_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
