# Generated by Django 3.0.8 on 2021-01-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201227_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='profit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
