# Generated by Django 3.0.8 on 2020-11-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201108_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='sellingPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
