# Generated by Django 3.0.8 on 2020-11-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_producthistory_sellingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
