# Generated by Django 3.0.8 on 2021-01-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210124_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Pending', 'Pending'), ('Awaiting Bank Transfer', 'Awaiting Bank Transfer'), ('Awaiting payment in store', 'Awaiting payment in store'), ('Awaiting payment on delivery', 'Awaiting payment on delivery'), ('Awaiting Indodana payment', 'Awaiting Indodana payment'), ('Reserved', 'Reserved'), ('Paid on website', 'Paid on website'), ('Paid in store', 'Paid in store'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refund in process', 'Refund in process'), ('Refunded', 'Refunded')], max_length=30),
        ),
    ]
