# Generated by Django 3.0.8 on 2020-11-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_producthistory_purchasepricetotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order'),
        ),
    ]
