# Generated by Django 3.0.8 on 2020-11-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201108_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discountedPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
