# Generated by Django 3.0.8 on 2020-11-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201112_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
